# Generated by Django 4.1.5 on 2023-03-02 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattable",
            name="create_at",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="作成日付"
            ),
        ),
        migrations.AlterField(
            model_name="usertable",
            name="create_at",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="作成日付"
            ),
        ),
    ]
