# Generated by Django 4.1.5 on 2023-03-02 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_chattable_create_at_alter_usertable_create_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="chatTable1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=20, verbose_name="表示名")),
                ("title", models.CharField(max_length=20, verbose_name="タイトル")),
                ("text", models.TextField(blank="True", verbose_name="コメント")),
                ("img", models.ImageField(upload_to="image/", verbose_name="画像ファイル")),
                (
                    "create_at",
                    models.TimeField(
                        default=django.utils.timezone.now, verbose_name="作成日付"
                    ),
                ),
            ],
        ),
    ]
