# Generated by Django 4.1.5 on 2023-03-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_chattable1_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="chatTable",
        ),
    ]
