# Generated by Django 4.1.5 on 2023-03-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_delete_chattable"),
    ]

    operations = [
        migrations.CreateModel(
            name="loginTable",
            fields=[
                (
                    "id",
                    models.CharField(
                        blank="False",
                        max_length=20,
                        primary_key="True",
                        serialize=False,
                        verbose_name="ユーザID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=20, null="False", verbose_name="パスワード"),
                ),
            ],
        ),
    ]
