# Generated by Django 4.1.5 on 2023-03-02 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_logintable"),
    ]

    operations = [
        migrations.CreateModel(
            name="chatTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=20, verbose_name="表示名")),
                ("title", models.CharField(max_length=20, verbose_name="タイトル")),
                ("text", models.TextField(blank="True", verbose_name="コメント")),
                (
                    "img",
                    models.ImageField(
                        blank="True", upload_to="image/", verbose_name="画像ファイル"
                    ),
                ),
                (
                    "create_at",
                    models.TimeField(
                        default=django.utils.timezone.now, verbose_name="作成日付"
                    ),
                ),
                ("genre", models.CharField(max_length=20, verbose_name="ジャンル")),
            ],
        ),
        migrations.DeleteModel(
            name="chatTable1",
        ),
    ]
